#!/bin/bash

#System Information
DATE=$(date +%F)
TIME=$(date +%T)
HN=$HOSTNAME
os=$(lsb_release -ds)
up=$(uptime -p)

#Hardware Information
CPU=$(lshw -c processor | grep -m 1 "product" | cut -d ':' -f 2 | tr -d '[:space:]')
CPU_SPEED=$(lshw -c processor | grep -m 1 "capacity" | cut -d ':' -f 2 | tr -d '[:space:]')
RAM=$(free -h | grep -E "Mem:" | awk '{print $2}')
DISKS=$(lsblk -o NAME,MODEL,SIZE --noheadings)
VIDEO_CARD=$(lspci -nn | grep -i VGA | cut -d ':' -f 3- | awk '{$1=$1};1')



#Network Information
FQDN=$(hostnamectl --static status)
HOST_ADDRESS=$(ip -o -4 addr show scope global | awk '/inet / {print $4}')
GATEWAY=$(ip route | awk '/default/ {print $3}')
DNS_SERVER=$(grep 'nameserver' /etc/resolv.conf | awk '{print $2}')

#Interface data
IP_INFO=$(ip -o -4 addr show)
INTERFACE_NAME=$(echo "$IP_INFO" | awk 'NR == 1 {print $2}')
IP_CIDR=$(echo "$IP_INFO" | awk '/scope global/ {print $2}')

#System Status
USERS=$(who | cut -d ' ' -f 1 | sort -u | paste -sd ', ')
DISK_SPACE=$(df -h | grep -v '^Filesystem' | awk '{print $6, $4}')
PROCESS_COUNT=$(ps --no-headers aux | wc -l)
read -r LOAD1 LOAD5 LOAD15 _ <<< $(</proc/loadavg)
LOAD_AVERAGES="$LOAD1 $LOAD5 $LOAD15"
MEMORY_ALLOCATION=$(free -h | awk '/Mem:/ {getline; print $2}')
LISTENING_PORTS=$(ss -tuln | awk 'NR > 1 {split($5, a, ":"); print a[2]}' | awk '!x[$0] {if (NR > 1) printf ","; printf $0; x[$0] = 1}')
UFW_RULES=$(sudo ufw status numbered | awk '{sub(/^[0-9]+ /, ""); print $2}')


echo "
System Report generated by $USER, $DATE/$TIME
 
System Information
------------------
Hostname: $HN
OS: $os
Uptime: $up

Hardware Information
--------------------
cpu: $CPU
Speed: $CPU_SPEED
Ram: $RAM
Disk(s):
$DISKS

Video: $VIDEO_CARD
 
Network Information
-------------------
FQDN: $FQDN
Host Address: $HOST_ADDRESS
Gateway IP: $GATEWAY
DNS Server: $DNS_SERVER
 
InterfaceName: $INTERFACE_NAME
IP Address: $IP_CIDR
 
System Status
-------------
Users Logged In: $USERS
Disk Space: 
$DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVERAGES
Memory Allocation: $MEMORY_ALLOCATION
Listening Network Ports: $LISTENING_PORTS
UFW Rules: $UFW_RULES
"
